# Generated by go2rpm 1.14.0.post0
%global debug_package %{nil}

# https://github.com/plamendelchev/geoip-block-ipset
%global goipath github.com/plamendelchev/geoip-block-ipset
Version:        0.1.0

%gometa -f

%global common_description %{expand:
Simple tool to whitelist countries in ipset.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           geoip-block-ipset
Release:        1%{?dist}
Summary:        Simple tool to whitelist countries in ipset

License:        GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:	systemd-rpm-macros
BuildRequires:  golang
BuildRequires:	go-rpm-macros
BuildRequires:	go-srpm-macros

Requires:       ipset
Requires:       iptables-nft

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_libexecdir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_libexecdir}/
install -m 0755 -vd %{buildroot}%{_unitdir}
install -m 0644 -vp systemd/*		        %{buildroot}%{_unitdir}/

%post
%systemd_post geoip-block-ipset.timer

%preun
%systemd_preun geoip-block-ipset.timer

%postun
%systemd_postun geoip-block-ipset.timer


%files
%license LICENSE
%doc README.md
%{_libexecdir}/geoip-block-ipset
%{_unitdir}/geoip-block-ipset.{service,timer}

%gopkgfiles

%changelog
